name = "LSPNeovim"
uuid = "42462c39-edde-4cdc-9c73-a9d3181f44a6"
authors = ["Expanding Man <savastio@protonmail.com>"]
version = "0.1.0"

[deps]
LanguageServer = "2b0e0bc5-e4fd-59b4-8912-456d1b03d8d7"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
SymbolServer = "cf896787-08d5-524d-9de7-132aaa0cb996"

[compat]
julia = "1"
LanguageServer = "3.1"
SymbolServer = "4.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
